### ISSUE TITLE
How to uninstall the tuptime installed by script?

### ISSUE THREAD

**Issue by TKONIY** [rfmoz/tuptime#77]
System ubuntu20.04LTS
My tuptime is installed by `https://git.io/tuptime-install.sh`
Now I want to uninstall it, how can I do it?

**Comment by rfmoz** [comment]
As you have Ubuntu, use the package manager to reinstall and uninstall it properly:
```
apt install tuptime
apt remove tuptime
```

**Comment by TKONIY** [comment]
But I have installed it by the script. Can this reinstall&uninstall help me correctly uninstall the uptime I previously installed?

**Comment by rfmoz** [comment]
The package manager will overwrite the files that the installation script copied and, besides, it provides the uninstall way.

**Comment by TKONIY** [comment]
Thanks!
