### ISSUE TITLE
Error on line 72 of dbcheck

### ISSUE THREAD

**Issue by bshor** [rfmoz/tuptime#78]
Hi, I'm trying to run the dbcheck script, but I'm getting the following error:

```
  File "/home/USER/Downloads/tuptime_dbcheck.py", line 72
    <title>tuptime/tuptime_dbcheck.py at master · rfmoz/tuptime · GitHub</title>
                                                ^
SyntaxError: invalid character '·' (U+00B7)
```

**Comment by rfmoz** [comment]
Hello,

It seems that you download the html website, not the real python script.

Please, get it from the raw url:

[https://raw.githubusercontent.com/rfmoz/tuptime/master/misc/scripts/tuptime_dbcheck.py](https://raw.githubusercontent.com/rfmoz/tuptime/master/misc/scripts/tuptime_dbcheck.py)

**Comment by bshor** [comment]
That was it. It worked!
