### ISSUE TITLE
hm

### ISSUE THREAD

**Issue by alexmyczko** [rfmoz/tuptime#83]
What do you think of https://github.com/alexmyczko/ruptime ?

**Comment by rfmoz** [comment]
Hi Alex,

It looks an interesting project and it must be under the tuptime README.md `Alternatives` list. Feel free to add a PR.

Appreciate the ruptime [list](https://github.com/alexmyczko/ruptime?tab=readme-ov-file#why-would-i-want-this) `Why would I want this?`, particularly the first point [it's simple](https://www.gkogan.co/blog/simple-systems/), also in line with [suckless](https://suckless.org/philosophy/) software.

Thanks,

**Comment by alexmyczko** [comment]
will do the pr, and also link to tuptime.
